FORMAT: 1A
HOST: http://{domain}.asknice.ly/api/v1

# AskNicely
Please login to your AskNicely account, select the book icon in the top menu to find the latest 
API docs with working examples for your account.