FORMAT: 1A
HOST: http://app.asknice.ly/api

# AskNicely
Subscribe a person and or trigger a survey question to them.


## Person [/person/add]
Add or update a single person. 

1. Name is firstname + lastname, email is required.
2. Segments (optional, default is general). Values are comma seperated.
3. Any field that does not match (segments, email, name, firstname, lastname) will be added as a custom field. Use this to store additional data about a person. 
4. triggeremail means we will email the question for this dashboard immediatly if "true".




### Create a Person [POST]
+ Request (application/json)
    + Headers
    
            X-apikey: demo
    + Body
        
            { "name": "John Smith", "email":"john@example.com", dashboard:"recommend", "triggeremail":false, "segments":"pro","mycustom_id":12 }
      

+ Response 201 (application/json)

        {id:12, "success":true,"msg":"added", emailed:false}

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }





## Notes Collection [/notes]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]
